# Generated by Django 3.1 on 2020-09-03 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ivtasu', '0003_auto_20200902_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='zanyatia',
            name='lector',
            field=models.CharField(default='default lector', max_length=50, unique=True, verbose_name='ФИО преподавателя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='days',
            name='day',
            field=models.SmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='days',
            name='spisok',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ivtasu.zanyatia', verbose_name='Предметы'),
        ),
    ]
