# Generated by Django 3.1 on 2020-09-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivtasu', '0005_auto_20200903_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zanyatia',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название занятия'),
        ),
    ]
