# Generated by Django 3.1 on 2020-09-03 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ivtasu', '0006_auto_20200903_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zanyatia',
            name='lector',
        ),
    ]
