# Generated by Django 3.1 on 2020-09-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivtasu', '0007_remove_zanyatia_lector'),
    ]

    operations = [
        migrations.AddField(
            model_name='zanyatia',
            name='lector',
            field=models.CharField(default='default', max_length=50, verbose_name='ФИО преподавателя'),
            preserve_default=False,
        ),
    ]
