# Generated by Django 3.1 on 2020-09-04 07:53

from django.db import migrations, models
from datetime import time

class Migration(migrations.Migration):

    dependencies = [
        ('ivtasu', '0008_zanyatia_lector'),
    ]

    operations = [
        migrations.AddField(
            model_name='zanyatia',
            name='time_end',
            field=models.TimeField(default=time(), verbose_name='Время конца пары'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zanyatia',
            name='time_start',
            field=models.TimeField(default=time(), verbose_name='Время начала пары'),
            preserve_default=False,
        ),
    ]
